
export const SIGN_IN = '/'
export const SIGN_UP = '/signup'
export const ADMIN = '/admin'
export const ACCOUNT = '/account'
export const WALL = '/wall'
export const PLANNING = '/planning'
export const STOCK = '/stock'
export const RECIPE = '/recipe'
export const CART = '/cart'
export const PASSWORD_FORGET = '/pw-forget'
